package models

import (
	"errors"

	"github.com/jinzhu/gorm"
)

var (
	// ErrNotFound is returned when a resource cannot be found
	// in the database.
	ErrNotFound = errors.New("models: resource not found")
)

func NewUserService(connectionInfo string) (*UserService, error) {
	db, err := gorm.Open("postgres", connectionInfo)
	if err != nil {
		return nil, err
	}
	db.LogMode(true)
	return &UserService{
		db: db,
	}, nil
}

type UserService struct {
	db *gorm.DB
}

// ByID will look up the user by the id input
// If user is found, return nil error
// If user is not found, return ErrNotFound
// If there is another erorr, return an error with
// more info about what went wrong.
// This may not be an error generated by the models package
//
// As a general rule, any error but ErrNotFound should
// probably result in a 500 error.
func (us *UserService) ByID(id uint) (*User, error) {
	var user User

	db := us.db.Where("id = ?", id)

	err := first(db, &user)
	return &user, err
}

// ByEmail will look up the user by the email input
// and returns that user. Similar to ByID above
func (us *UserService) ByEmail(email string) (*User, error) {
	var user User

	db := us.db.Where("email = ?", email)

	err := first(db, &user)
	return &user, err
}

func first(db *gorm.DB, user *User) error {
	err := db.First(user).Error
	if err == gorm.ErrRecordNotFound {
		return ErrNotFound
	}
	return err
}

// Create creates a provided user and backfill data
// like the ID, createdat, updatedat, deletedat fields
func (us *UserService) Create(user *User) error {
	return us.db.Create(user).Error
}

// Update updates a provided user with all the data
// in the provided user object.
func (us *UserService) Update(user *User) error {
	return us.db.Save(user).Error
}

// Close closes the UserService database connection
func (us *UserService) Close() error {
	return us.db.Close()
}

// DestructiveReset drops the user table and rebuilds it
func (us *UserService) DestructiveReset() {
	us.db.DropTableIfExists(&User{})
	us.db.AutoMigrate(&User{})
}

// User is our app user model
type User struct {
	gorm.Model
	Name  string
	Email string `gorm:"not null;unique_index"`
}
